include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - node_modules/**
  errors:
    unused_import: error
    unused_local_variable: warning
    dead_code: warning
    unused_element: warning
    unused_field: warning

linter:
  rules:
    - avoid_relative_lib_imports
    - avoid_unused_constructor_parameters
    - unnecessary_string_interpolations
    - unnecessary_this
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - unnecessary_null_aware_assignments
    - unnecessary_nullable_for_final_variable_declarations
