// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGYPvPeXVT7Vm48p33-Wc_yAK_RHN_Wok',
    appId: '1:1003850167458:web:5ef2049653a7866e05d3fb',
    messagingSenderId: '1003850167458',
    projectId: 'account-flutter-58a59',
    authDomain: 'account-flutter-58a59.firebaseapp.com',
    databaseURL: 'https://account-flutter-58a59-default-rtdb.firebaseio.com',
    storageBucket: 'account-flutter-58a59.firebasestorage.app',
    measurementId: 'G-KQEKVGNYRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUAA-EUusYz5p6yIFpVsUS13pqj6nZQKE',
    appId: '1:1003850167458:android:071f27e46e9a11a105d3fb',
    messagingSenderId: '1003850167458',
    projectId: 'account-flutter-58a59',
    databaseURL: 'https://account-flutter-58a59-default-rtdb.firebaseio.com',
    storageBucket: 'account-flutter-58a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLhzB1ugiT3RtrgpWHsrS5FJ8zMb3zkA8',
    appId: '1:1003850167458:ios:3f0454159e1aaf9b05d3fb',
    messagingSenderId: '1003850167458',
    projectId: 'account-flutter-58a59',
    databaseURL: 'https://account-flutter-58a59-default-rtdb.firebaseio.com',
    storageBucket: 'account-flutter-58a59.firebasestorage.app',
    iosBundleId: 'com.example.account',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLhzB1ugiT3RtrgpWHsrS5FJ8zMb3zkA8',
    appId: '1:1003850167458:ios:3f0454159e1aaf9b05d3fb',
    messagingSenderId: '1003850167458',
    projectId: 'account-flutter-58a59',
    databaseURL: 'https://account-flutter-58a59-default-rtdb.firebaseio.com',
    storageBucket: 'account-flutter-58a59.firebasestorage.app',
    iosBundleId: 'com.example.account',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGYPvPeXVT7Vm48p33-Wc_yAK_RHN_Wok',
    appId: '1:1003850167458:web:82625ccb03dc738405d3fb',
    messagingSenderId: '1003850167458',
    projectId: 'account-flutter-58a59',
    authDomain: 'account-flutter-58a59.firebaseapp.com',
    databaseURL: 'https://account-flutter-58a59-default-rtdb.firebaseio.com',
    storageBucket: 'account-flutter-58a59.firebasestorage.app',
    measurementId: 'G-1T9G5ZFVL9',
  );
}
